accounts/urls.py
from django.urls import path
from .views import (
    show,
    ProfileView,
    ProfileEditView,
    AddFollwer,
    RemoveFollwer,
    UserSearch,
    ListFollowers,
    ListThreads,
    CreateThread,
    ThreadView,
    CreateMessage,
)
urlpatterns =[
    path('',show,name='index'),
    path('profile/<slug:name>',ProfileView.as_view(),name='profile'),
    path('profile/edit/<int:pk>/',ProfileEditView.as_view(),name='profile-edit'),
    path('profile/<int:pk>/followers/',ListFollowers.as_view(),name='list-followers'),
    path('profile/<int:pk>/followers/add',AddFollwer.as_view(),name='add-follower'),
    path('profile/<int:pk>/followers/remove',RemoveFollwer.as_view(),name='remove-follower'),
    path('search/',UserSearch.as_view(),name='profile-search'),

    path('inbox/', ListThreads.as_view(), name='inbox'),
    path('inbox/create-thread/', CreateThread.as_view(), name='create-thread'),
    path('inbox/<int:pk>/', ThreadView.as_view(), name='thread'),
    path('inbox/<int:pk>/create-message/', CreateMessage.as_view(), name='create-message'),
    
]

blog/urls.py
from unicodedata import name
from django.urls import path
from . import views


app_name = 'blog'
urlpatterns = [
    # post views  
    path('', views.post_list, name='post_list'),
    path('q/', views.search_post, name='search_post'),
    path('new/', views.post_create, name='post_create'),
    path('<slug:post>/edit/', views.post_edit, name='post_edit'),
    path('<slug:post>/',views.post_detail, name='post_detail'),
    path('<slug:post>/del/',views.deletePost, name='post_del'),
    path('<int:post_id>/share/',views.post_share, name='post_share'),
    path('tag/<slug:tag_slug>/',views.post_list, name='post_list_by_tag'),
    path('<slug:post>/like',views.like_view,name='like_post'),
    

]

blogForum/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('', include('accounts.urls')),
    path('b/', include('blog.urls')),
    path('ask/', include('forum.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
]


if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

forum/urls.py
from django.urls import path
from . import views

app_name = 'forum'
urlpatterns=[
    path('',views.home,name='home'),
    path('tags',views.tags,name='tags'),
    path('tag/<str:tag>/',views.tag,name='tag'),
    path('ask-question',views.ask_form,name='ask-question'),
    path('unanswered',views.give_answer,name='unanswered'),
    path('save-comment',views.save_comment,name='save-comment'),
    path('<int:pk>/ans_edit/', views.answer_edit, name='ans_edit'),
    path('<int:pk>/ans_del/',views.deleteAns, name='ans_del'),
    path('<slug:slug>',views.detail,name='detail'),
    path('<slug:slug>/edit/', views.post_edit, name='ques_edit'),
    path('<slug:slug>/del/',views.deletePost, name='ques_del'),
    path('<int:id>/<int:pk>/save-upvote',views.save_upvote,name='save-upvote'),
    path('<int:id>/<int:pk>/save-downvote',views.save_downvote,name='save-downvote'),
    
    
    
]

accounts/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.urls import reverse

# Create your models here.


class UserProfile(models.Model):
    user=models.OneToOneField(User,primary_key=True,verbose_name='user',related_name='profile',on_delete=models.CASCADE)
    name=models.SlugField()
    nickname=models.CharField(max_length=30)
    bio=models.TextField(max_length=500,blank=True,null=True)
    birth_date=models.DateField(null=True,blank=True)
    location=models.CharField(max_length=100,blank=True,null=True)
    picture=models.ImageField(upload_to='uploads/profile_pictures',default='uploads/profile_pictures/default.jpg')
    followers=models.ManyToManyField(User,blank=True,related_name='followers')

    def get_absolute_url(self):
        return reverse('profile', args=[self.name])



@receiver(post_save,sender=User)
def create_user_profile(sender,instance,created,**kwargs):
    if created:
        UserProfile.objects.create(user=instance)


@receiver(post_save,sender=User)
def save_user_profile(sender,instance,**kwargs):
    instance.profile.name=User.get_username(instance)
    instance.profile.nickname=instance.profile.name
    instance.profile.save()




class ThreadModel(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='+')
	receiver = models.ForeignKey(User, on_delete=models.CASCADE, related_name='+')


class MessageModel(models.Model):
	thread = models.ForeignKey('ThreadModel', related_name='+', on_delete=models.CASCADE, blank=True, null=True)
	sender_user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='+')
	receiver_user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='+')
	body = models.CharField(max_length=1000)
	image = models.ImageField(upload_to='uploads/message_photos', blank=True, null=True)
	date = models.DateTimeField(default=timezone.now)
	is_read = models.BooleanField(default=False)

accounts/forms.py
from django import forms
from .models import MessageModel

 

class ThreadForm(forms.Form):
    username = forms.CharField(label='', max_length=100)

class MessageForm(forms.ModelForm):
    body = forms.CharField(label='', max_length=1000)

    image = forms.ImageField(required=False)

    class Meta:
        model = MessageModel
        fields = ['body', 'image']


 
            

accounts/views.py
from email.mime import image
from urllib.request import Request
from django.shortcuts import render,redirect
from django.views import View
from .models import UserProfile,ThreadModel,MessageModel
from .forms import *
from django.views.generic.edit import UpdateView,DeleteView
from django.urls import reverse_lazy
from django.contrib.auth.mixins import UserPassesTestMixin,LoginRequiredMixin
from django.http import HttpResponseRedirect,HttpResponse
from django.db.models import Q
from django.contrib.auth.models import User
from django.contrib import messages
from django.utils import timezone
from blog.models import *
from forum.models import *
# Create your views here.

def show(request):
    return render(request,'index.html')




class ProfileView(LoginRequiredMixin,View):
    def get(self,request,name,*args,**kwargs):
        profile=UserProfile.objects.get(name=name)
        user=profile.user
       
        posts = Post.objects.filter(author=user)
        quests=Question.objects.filter(user=user).order_by('-id')
        answers=Answer.objects.filter(user=user).order_by('-id')

        followers=profile.followers.all()

        is_following=False
        for follower in followers:
            if follower==request.user:
                is_following=True
                break

        number_of_followers=len(followers)



        context={
            'user':user,
            'profile':profile,
            'posts':posts,
            'number_of_followers':number_of_followers,
            'is_following':is_following,
            'quests':quests,
            'answers':answers,
        }

        return render(request,'accounts/profile.html',context)

        

class ProfileEditView(LoginRequiredMixin,UserPassesTestMixin,UpdateView):
    model=UserProfile
    fields=['nickname','bio','birth_date','location','picture']
    template_name='accounts/profile_edit.html'

    def get_success_url(self):
        pk=self.kwargs['pk']
        profile=UserProfile.objects.get(pk=pk)
        name=profile.name
        return reverse_lazy('profile',kwargs={'name':name})
         

    def test_func(self):
        profile=self.get_object()
        return self.request.user == profile.user 




class AddFollwer(LoginRequiredMixin,View):
    def post(self,request,pk,*args,**kwargs):
        profile=UserProfile.objects.get(pk=pk)
        profile.followers.add(request.user)


        return redirect('profile',name=profile.name)



class RemoveFollwer(LoginRequiredMixin,View):
    def post(self,request,pk,*args,**kwargs):
        profile=UserProfile.objects.get(pk=pk)
        profile.followers.remove(request.user)

        return redirect('profile',name=profile.name)
 
class UserSearch(View):
    def get(self,request,*args,**kwargs):
        query=self.request.GET.get('query')
        profile_list=UserProfile.objects.filter(
            Q(user__username__icontains=query)
        )
        context={
            'profile_list':profile_list,
        }
        return render(request,'accounts/search.html',context)


        


class ListFollowers(View):
    def get(self,request,pk,*args,**kwargs):
        profile=UserProfile.objects.get(pk=pk)
        followers=profile.followers.all()

        context={
            'profile':profile,
            'followers':followers,
        }

        return render(request,'accounts/followers_list.html',context)



class ListThreads(View):
    def get(self, request, *args, **kwargs):
        threads = ThreadModel.objects.filter(Q(user=request.user) | Q(receiver=request.user))

        context = {
            'threads': threads
        }

        return render(request, 'accounts/inbox.html', context)


class CreateThread(View):
    def get(self, request, *args, **kwargs):
        form = ThreadForm()

        context = {
            'form': form
        }

        return render(request, 'accounts/create_thread.html', context)

    def post(self, request, *args, **kwargs):
        form = ThreadForm(request.POST)

        username = request.POST.get('username')

        try:
            receiver = User.objects.get(username=username)
            if ThreadModel.objects.filter(user=request.user, receiver=receiver).exists():
                thread = ThreadModel.objects.filter(user=request.user, receiver=receiver)[0]
                return redirect('thread', pk=thread.pk)
            elif ThreadModel.objects.filter(user=receiver, receiver=request.user).exists():
                thread = ThreadModel.objects.filter(user=receiver, receiver=request.user)[0]
                return redirect('thread', pk=thread.pk)

            if form.is_valid():
                thread = ThreadModel(
                    user=request.user,
                    receiver=receiver
                )
                thread.save()

                return redirect('thread', pk=thread.pk)
        except:
            messages.error(request,'User not exist')
            return redirect('create-thread')



class ThreadView(View):
    def get(self, request, pk, *args, **kwargs):
        form = MessageForm()
        thread = ThreadModel.objects.get(pk=pk)
        message_list = MessageModel.objects.filter(thread__pk__contains=pk)
        context = {
            'thread': thread,
            'form': form,
            'message_list': message_list
        }

        return render(request, 'accounts/thread.html', context)



class CreateMessage(View):
    def post(self, request, pk, *args, **kwargs):
        form=MessageForm(request.POST,request.FILES)
        thread = ThreadModel.objects.get(pk=pk)
        if thread.receiver == request.user:
            receiver = thread.user
        else:
            receiver = thread.receiver

        if form.is_valid():
            message=form.save(commit=False)
            message.thread=thread
            message.sender_user=request.user
            message.receiver_user=receiver
            message.save()
 

        return redirect('thread', pk=pk)

templates/accounts/base.html
{% load static %}


<!doctype html>
<html lang="en">
  <head>
    <title>{% block head_title %}{% endblock %}</title>
    {% block extra_head %}
    {% endblock %}
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
     <!-- Font Awesome -->
     <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
     <!-- Google Fonts -->
     <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap">
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/e20c33fe72.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}?{% now 'U' %}">
    
  </head>
  <body>
    {% include 'navbar.html' %}
    {% block body %}
     
        {% if messages %}
        <div class="row justify-content-center pt-3">
          <div class="col-md-6">
            {% for message in messages %}
            <div class="alert alert-primary" role="alert">{{message}}</div>
            {% endfor %}
        </div>
        </div>
        {% endif %}

      {% block content %}
      {% endblock content %}
    {% endblock %}

    {% block extra_body %}
    {% endblock %}


    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <script type="text/javascript" src="{% static 'js/main.js' %}">
    </script>

  </body>
</html>

templates/accounts/create_thread.html
{% extends 'accounts/base.html' %}
{% load crispy_forms_tags %}

{% block content %}

<div class="container">
	<div class="row">
		<div class="col-md-12 p-5">
			<a href="{% url 'inbox' %}" class="btn btn-light">Back to Your Inbox</a>
		</div>
	</div>

	<div class="row">
		<div class="col-md-12 p-5">
			<h3>Start a Conversation!</h3>
		</div>
	</div>

	<div class="row justify-content-center mt-3 mb-5">
		<div class="col-md-5 col-sm-12">
			{% if messages %}
				{% for message in messages %}
					<div class="alert alert-danger">
						{{ message }}
					</div>
				{% endfor %}
			{% endif %}
			
			<form method="POST">
				{% csrf_token %}
				<p>Enter the username for the person you would like to talk to.</p>
				{{ form | crispy }}
				<div class="d-grid gap-2">
					<button class="btn btn-success mt-3" type="submit">Continue</button>
				</div>
			</form>
		</div>
	</div>
</div>

{% endblock content %}

templates/accounts/followers_list.html
{% extends 'accounts/base.html' %}

{% block content %}
<div class="container">
    <div class="row mt-5">
        <div class="col-md-3 col-sm-6">
            <a href="{% url 'profile' profile.name %}" class="btn btn-light">Back to Profile</a>
        </div>
    </div>

    <div class="row justify-content-center mt-3">
    	<div class="col-md-5 col-sm-12">
    		{% if profile.name %}
    		<h3>Followers for {{ profile.name }}</h3>
    		{% else %}
    		<h3>Followers for @{{ profile.user.username }}</h3>
    		{% endif %}
    	</div>
    </div>

    {% for follower in followers %}
    <div class="row justify-content-center">
    	<div class="col-md-5 col-sm-12 position-relative my-3">
    		<a href="{% url 'profile' follower.profile.name %}" style="text-decoration: none;"><img class="rounded-circle post-img" height="60" width="60" src="{{ follower.profile.picture.url }}" /></a>
    		<a href="{% url 'profile' follower.profile.name %}" style="text-decoration: none;"><h5 class="mt-3">@{{ follower.username }}</h5></a>

    	</div>
    </div>
    {% endfor %}
</div>
{% endblock content %}

templates/accounts/inbox.html
{% extends 'accounts/base.html' %}

{% block content %}

<div class="container">
	<div class="row">
		<div class="col-md-12 p-4">
			<h3>Your Conversations</h3>
		</div>
	</div>

	<div class="row">
		<div class="col-md-12 p-4">
			<form method="GET" action="{% url 'create-thread' %}">
				<button class="btn btn-light p-3" type="submit">Start a Conversation</button>
			</form>
		</div>
	</div>

	{% for thread in threads.all %}
	<div class="row mb-3">
		<div class="card col-md-12 p-3 shadow-sm">
			<h5><i class="far fa-envelope inbox-icon"></i> @{{ thread.user }} - @{{ thread.receiver }}</h5>
			<a class="stretched-link" href="{% url 'thread' thread.pk %}"></a>
		</div>
	</div>
	{% endfor %}
</div>

{% endblock content %}

templates/accounts/profile.html
{% extends 'accounts/base.html' %}
{% load blog_tags %}
{% load urlify %}


{% block content %}
<div class="container">
    <div class="row mt-5">
        <div class="col-md-3 col-sm-6">
            <a href="{% url 'index' %}" class="btn btn-light">Back to Feed</a>
        </div>
    </div>

    <div class="row justify-content-center mt-5">
        <div class="card shadow-sm col-md-8 col-sm-12 border-bottom px-5 pt-3">
            <div class="text-center">
                {% if profile.picture.url %}
                <img src="{{ profile.picture.url }}" class="rounded-circle" width="100" height="100" />
                {% endif %}
                {% if profile.name %}
                <h3 class="py-4">{{ profile.name }}
                    <span>
                        {% if request.user == user %}
                            <a href="{% url 'profile-edit' profile.pk %}" class="edit-color"><i class="far fa-edit"></i></a>
                        {% endif %}
                    </span>
                    {% else %}
                    <h3 class="py-4">{{ user.username }}
                        <span>
                            {% if request.user == user %}
                                <a href="{% url 'profile-edit' profile.pk %}" class="edit-color"><i class="far fa-edit"></i></a>
                            {% endif %}
                        </span>
                    </h3>
                    {% endif %}
                </h3>
            </div>

            <h3>{{ profile.nickname }}</h3>

            {% if profile.bio %}
            <p>{{ profile.bio }}</p>
            {% endif %}

            <div class="mb-3">
                <a href="{% url 'list-followers' profile.pk %}" style="text-decoration: none;">Followers: {{ number_of_followers }}</a>
                
            </div>
        </div>
    </div>

    <div class="row justify-content-center mt-5">
        <div class="card shadow-sm col-md-8 col-sm-12 border-bottom px-5 py-3">
            {% if profile.location %}
            <p>Location: {{ profile.location }}</p>
            {% endif %}

            {% if profile.birth_date %}
            <p>Birthday: {{ profile.birth_date }}</p>
            {% endif %}

            {% if user == request.user %}
                {% else %}
                {% if is_following %}
                    <form method="POST" action="{% url 'remove-follower' profile.pk %}">
                        {% csrf_token %}
                        <button class="btn btn-outline-danger" type="submit">Unfollow</button>
                    </form>
                    {% else %}
                    <form method="POST" action="{% url 'add-follower' profile.pk %}">
                        {% csrf_token %}
                        <button class="btn btn-outline-success" type="submit">Follow</button>
                    </form>
                {% endif %}
            {% endif %}
        </div>
    </div>

    
    <div class="row justify-content-center mt-5">
        <div class="card shadow-sm col-md-8 col-sm-12 border-bottom px-5 py-3">
            <div class="d-flex align-items-start">
                <div class="nav flex-column nav-pills me-3" id="v-pills-tab" role="tablist" aria-orientation="vertical">
                  <button class="nav-link active" id="v-pills-home-tab" data-bs-toggle="pill" data-bs-target="#v-pills-home" type="button" role="tab" aria-controls="v-pills-home" aria-selected="true">Questions</button>
                  <button class="nav-link" id="v-pills-profile-tab" data-bs-toggle="pill" data-bs-target="#v-pills-profile" type="button" role="tab" aria-controls="v-pills-profile" aria-selected="false">Answers</button>
                  
                </div>
                <div class="tab-content" id="v-pills-tabContent">
                  <div class="tab-pane fade show active" id="v-pills-home" role="tabpanel" aria-labelledby="v-pills-home-tab">
                    <div class="card" style="width: 18rem">
                        <div class="card-header">
                            <h5>Questions ( <span>{{quests.count}}</span> )</h5>
                        </div>
                        <ul class="list-group list-group-flush">
                        {% for quest in quests %}
                        <li class="list-group-item">
                            <a href="{% url 'forum:detail' quest.slug %}" style=" text-decoration: none;">{{ quest.title }}</a>
                        </li>
                        {% endfor %}
                        </ul>
                      </div>
                  </div>

                  <div class="tab-pane fade" id="v-pills-profile" role="tabpanel" aria-labelledby="v-pills-profile-tab">
                    <div class="card">
                        <h5 class="card-header">Answers (<span">{{answers.count}}</span>)</h5>
                        <div class="card-body">
                            <table class="table table-bordered">
                                <tr>
                                    <th>Question</th>
                                    <th>Answer</th>
                                </tr>
                                {% for ans in answers %}
                                <tr>
                                    <td><a href="{% url 'forum:detail' ans.question.slug %}" style=" text-decoration: none;">{{ans.question.title|safe }}</a></td>
                                    <td><a href="{% url 'forum:detail' ans.question.slug %}" style=" text-decoration: none;">{{ans.detail|safe}}</a></td>
                                </tr>
                                {% endfor %}
                            </table>
                        </div>
                    </div>
                  </div>
                 
                </div>
              </div>
        </div>
    </div>

    {% for post in posts %}
    <div class="row justify-content-center mt-5">
        <div class="col-md-8 col-sm-12 border-bottom">
            <div>
                <a href="{% url 'profile' post.author.profile.pk %}">
                    <img class="round-circle post-img" height="30" width="30" src="{{ post.author.profile.picture.url }}" />
                </a>
                <p class="post-text">
                    <a class="text-primary post-link" href="{% url 'profile' post.author.profile.pk %}">@{{ post.author }}</a> {{ post.created }}
                </p>
            </div>
            <div class="position-relative">
                {{ post.title }}
                {% if post.image.count > 0 %}
                  <div class="row">
                    {% for img in post.image.all %}
                        <div class="col-md-4 col-xs-12">
                            <img src="{{ img.image.url }}" class="post-image" />
                        </div>
                    {% endfor %}
                  </div>
                {% endif %}
                <p>{{ post.body|markdown|truncatewords_html:20 }}</p>
                <a href="{% url 'blog:post_detail' post.slug %}" class="stretched-link"></a>
            </div>
 
        </div>
    </div>
    {% endfor %}

</div>
{% endblock content %}

templates/accounts/profile_edit.html
{% extends 'accounts/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container">
    <div class="row mt-5">
        <div class="col-md-5 col-sm-6">
            <a href="{% url 'profile' object.pk %}" class="btn btn-light">Back To Profile</a>
        </div>
    </div>

    <div class="row justify-content-center mt-3">
        <div class="col-md-5 col-sm-12 border-bottom">
            <h5>Update Your Profile</h5>
        </div>
    </div>

    <div class="row justify-content-center mt-3 mb-5">
        <div class="col-md-5 col-sm-12 border-bottom">
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form | crispy }}
                <div class="d-grid gap-2">
                    <button class="btn btn-success mt-3">Submit!</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

templates/accounts/search.html
{% extends 'accounts/base.html' %}

{% block content %}
<div class="container">
    <div class="row mt-5">
        <div class="col-md-5 col-sm-6">
            <a href="{% url 'index' %}" class="btn btn-light">Back To Feed</a>
        </div>
    </div>
    
    {% for profile in profile_list %}
        <div class="row justify-content-center mt-3">
            <div class="col-md-5 col-sm-12 border-bottom position-relative">
              
                <a href="{% url 'profile' profile.name %}">
                    <img class="round-circle" style="float: left; margin-right: 1rem ;" height="30" width="30" src="{{  profile.picture.url }}" />
                </a>
                <p>
                    <a style="text-decoration: none" class="text-primary"
                        href="{% url 'profile' profile.name %}">@{{ profile.user }}
                    </a>
                </p>
              
                <p><a style="text-decoration: none;" class="text-primary" href="{% url 'profile' profile.name %}">@{{ profile.user }}</a></p>
                {% if profile.location %}
                    <p>{{ profile.location }}</p>
                {% endif %}
                <p>Followers: {{ profile.followers.all.count }}</p>
            </div>
        </div>
    {% endfor %}
</div>
{% endblock content %}

templates/accounts/thread.html
{% extends 'accounts/base.html' %}
{% load crispy_forms_tags %}

{% block content %}

<div class="container">
	<div class="row">
		<div class="card col-md-12 mt-5 p-3 shadow-sm">
			{% if thread.receiver == request.user %}
				<h5>@{{ thread.user }}</h5>
			{% else %}
				<h5>@{{ thread.receiver }}</h5>
			{% endif %}
		</div>
	</div>

	{% if message_list.all.count == 0 %}
	<div class="row my-5">
		<div class="col-md-12">
			<p class="empty-text">No Messages</p>
		</div>
	</div>
	{% endif %}

	{% for message in message_list %}
	<div class="row">
		{% if message.receiver_user == request.user %}
		<div class="col-md-12 my-1">
			{% if message.image %}
			<div>
				<img src="{{ message.image.url }}" class="message-image" />
			</div>
			{% endif %}
			<div class="received-message my-1">
				<p>{{ message.body }}</p>
			</div>
		</div>
			{% elif message.sender_user == request.user %}
			<div class="col-md-12 offset-6">
				{% if message.image %}
				<div class="message-receiver-container ms-auto">
					<img src="{{ message.image.url }}" class="message-image" />
				</div>
				{% endif %}
				<div class="sent-message my-1">
					<p>{{ message.body }}</p>
				</div>
			</div>
			{% endif %}
		</div>
	{% endfor %}

	<div class="row">
		<div class="card col-md-12 p-3 shadow-sm">
			<form method="POST" action="{% url 'create-message' thread.pk %}" enctype="multipart/form-data">
				{% csrf_token %}
				{{ form | crispy }}

				<div class="d-grid gap-2 mt-3">
					<button class="btn btn-light" type="submit">Send Message</button>
				</div>
			</form>
		</div>
	</div>
</div>


{% endblock content %}