blog/urls.py
from unicodedata import name
from django.urls import path
from . import views


app_name = 'blog'
urlpatterns = [
    # post views  
    path('', views.post_list, name='post_list'),
    path('q/', views.search_post, name='search_post'),
    path('new/', views.post_create, name='post_create'),
    path('<slug:post>/edit/', views.post_edit, name='post_edit'),
    path('<slug:post>/',views.post_detail, name='post_detail'),
    path('<slug:post>/del/',views.deletePost, name='post_del'),
    path('<int:post_id>/share/',views.post_share, name='post_share'),
    path('tag/<slug:tag_slug>/',views.post_list, name='post_list_by_tag'),
    path('<slug:post>/like',views.like_view,name='like_post'),
    

]

blogForum/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('', include('accounts.urls')),
    path('b/', include('blog.urls')),
    path('ask/', include('forum.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
]


if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager
from django.utils.text import slugify
from django.db.models.signals import pre_save
from ckeditor.fields import RichTextField
# Create your models here.


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset()\
            .filter(status='published')


class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = models.CharField(max_length=250)
    # slug = models.SlugField(max_length=250, unique_for_date='publish')
    slug = models.SlugField(unique=True)
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='blog_posts')
    # body = models.TextField()
    body=RichTextField(blank=True,null=True)
    image=models.ImageField(null=True,blank=True,upload_to='blog_post')
    # height_field = models.IntegerField(default=0)
    # width_field = models.IntegerField(default=0)
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(
        max_length=10, choices=STATUS_CHOICES, default='published')
    likes=models.ManyToManyField(User,related_name='like_post')
    tags = TaggableManager(blank=True)


    objects = models.Manager()
    published = PublishedManager()

    def total_likes(self):
        return self.likes.count()

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.slug])

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey(Post,on_delete=models.CASCADE,related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)
    class Meta:
        ordering = ('created',)
    def __str__(self):
        return f'Comment by {self.name} on {self.post}'

 

from .utils import unique_slug_generator

def pre_save_post_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        # instance.slug = create_slug(instance)
        instance.slug = unique_slug_generator(instance)



pre_save.connect(pre_save_post_receiver, sender=Post)

blog/forms.py
from django import forms
from .models import Comment, Post
from taggit.forms import TagWidget
# from pagedown.widgets import PagedownWidget

class PostForm(forms.ModelForm):
    # body = forms.CharField(widget=PagedownWidget())
    class Meta:
        model=Post
        fields=['title','body','image','tags']
        widgets = {
            'tags': TagWidget(),
             
        }
        labels={
            'body':'',
        }


class EmailPostForm(forms.Form):
    # name = forms.CharField(max_length=25)
    # email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['body']
    

    

blog/views.py
from email import message
from importlib.resources import contents
from re import search
from django.contrib import messages
from multiprocessing import context
from urllib import request
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from .models import Post, Comment
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .forms import EmailPostForm, CommentForm, PostForm
from django.core.mail import send_mail
from taggit.models import Tag
from django.db.models import Count
import os
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from django.db.models import Q

# Create your views here.

def search_post(request):
    query=request.GET.get("q")
    result=None
    lookups=Q(title__icontains=query) | Q(body__icontains=query)
    result=Post.objects.filter(lookups)
    content={
        "searched":query,
        "result":result
    }
    return render(request,'blog/post/search.html',content)
    


@login_required
def like_view(request,post):
    p=get_object_or_404(Post,slug=post,status='published')
    liked=False
    if p.likes.filter(id=request.user.id).exists():
        p.likes.remove(request.user)
        liked=False
    else:
        p.likes.add(request.user)
        liked=True

    return redirect(p.get_absolute_url())

@login_required
def post_create(request):
    form = PostForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.author = request.user
        instance.save()
        form.save_m2m()
      
        messages.success(request, "Successfully Created")
        return redirect(instance.get_absolute_url())
    context = {
        "form": form,
        'page': 'new-post',
      
    }
    return render(request, "blog/post/post_form.html", context)


@login_required
def post_edit(request, post):

    page = 'post-edit'
    p = get_object_or_404(Post, slug=post, status='published')
    if p.author.id != request.user.id:
        raise PermissionDenied
    form = PostForm(instance=p)

    if request.method == 'POST':
        form = PostForm(request.POST,
                        request.FILES,
                        instance=p)
        if form.is_valid():
            form.save()
            print(p.tags.all())
            messages.success(request, f'Post Updated')
            return redirect(p.get_absolute_url())

    else:
        form = PostForm(instance=p)

    context = {
        'form': form,
        'page': page,
        'post': p,
    }

    return render(request, 'blog/post/detail.html', context)


@login_required
def deletePost(request, post):
    # p=Post.objects.get(slug=slug)

    p = get_object_or_404(Post, slug=post, status='published')
    if p.author.id != request.user.id:
        raise PermissionDenied

    if request.method == 'POST':
        p.delete()
        return redirect('blog:post_list')

    context = {'object': p}
    return render(request, 'blog/post/postdelete.html', context)


def post_list(request, tag_slug=None):
    object_list = Post.published.all()
    tag = None

    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])

    paginator = Paginator(object_list, 8)  # 3 posts in each page
    page = request.GET.get('page')

    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        posts = paginator.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        posts = paginator.page(paginator.num_pages)

    # posts = Post.published.all()
    context = {
        'posts': posts,
        'page': page,
        'tag': tag
    }
    return render(request, 'blog/post/list.html', context)

@login_required
def post_detail(request,  post):
    post = get_object_or_404(Post, slug=post,
                             status='published',
                             )
    # List of active comments for this post
    comments = post.comments.filter(active=True)

    new_comment = None

    if request.method == 'POST':
        # A comment was posted
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.name=request.user
           
        # # Create Comment object but don't save to database yet
            new_comment.post = post
        # Assign the current post to the comment
            new_comment.save()
        # Save the comment to the database
            return redirect(post.get_absolute_url())

    else:
        comment_form = CommentForm()

    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(
        tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags'))\
        .order_by('-same_tags', '-publish')[:4]

    total_likes=post.total_likes()
    
    liked=False
    if post.likes.filter(id=request.user.id).exists():
        liked=True
   
    
    

    context = { 
        'post': post,
        'comments': comments,
        'new_comment': new_comment,
        'comment_form': comment_form,
        'similar_posts': similar_posts,
        'total_likes':total_likes,
        'liked':liked
    }

    return render(request, 'blog/post/detail.html', context)


@login_required
def post_share(request, post_id):
    # Retrive post by id
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False

    if request.method == 'POST':
        form = EmailPostForm(request.POST)
        if form.is_valid():
            # Form feilds passsed validation.
            cd = form.cleaned_data
            # send mail
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = f"{ request.user } recommends you read {post.title}"
            message = f"Read {post.title} at {post_url}\n\n" \
                      f"{request.user}\'s comments: {cd['comments']}"
            send_mail(subject, message, os.environ.get(
                'EMAIL_USER'), [cd['to']])
            sent = True

    else:
        form = EmailPostForm()
    context = {
        'post': post,
        'form': form,
        'sent': sent
    }

    return render(request, 'blog/post/share.html', context)

templates/blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}
{% load blog_tags %}
{% load urlify %}
{% load crispy_forms_tags %}

{% block head_extra %}
{{form.media}}
{% endblock %}

{% block title %}
{{ post.title }}
{% endblock %}

{% block content %}
<div class="post-details-containter">
    <div class="post-details-title-bar">
        <img class="profile-img" src="{{ post.author.profile.picture.url }}" />
        <h1 class="post-details-title">{{ post.title }}</h1>
    </div>
    <p class="date">
        Published {{ post.publish }} by {{ post.author }}
    </p>

    <div class="tag-container">
        {% for tag in post.tags.all %}
        <a class="details-tags" href="{% url 'blog:post_list_by_tag' tag.slug %}">
            {{ tag.name }}
        </a>
        {% endfor %}
    </div>

    {% if page != 'post-edit' %}

    {% if post.image %}
    <img class="imgr" src='{{ post.image.url }}' />
    {% endif %}

    <div class="post-details-body">
        {{ post.body|markdown }}
    </div>

    {% endif %}
</div>

{% if page == 'post-edit' %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <fieldset class="form-group">
        <legend class="border-bottom mb-4">Edit your post</legend>
        {{ form | crispy }}
    </fieldset>
    <div class="form-group">
        <button class="btn btn-outline-info" type="submit">Update</button>
    </div>
</form>
{% endif %}

<form method="POST" action="{% url 'blog:like_post' post.slug %}">
    {% csrf_token %}

    {% if liked %}
    <p class="unlike-btn"><button type="submit" , name='post_id' , value='{{ post.id }}'
            class="btn btn-danger btn-sm">Unlike</button> - {{ total_likes }} Likes</p>
    {% else %}
    <p class="like-btn"><button type="submit" , name='post_id' , value='{{ post.id }}'
            class="btn btn-primary btn-sm">Like</button> - {{ total_likes }} Likes</p>
    {% endif %}
</form>

<div class="activities-bar">
    <a class="activities-bar-item" href="{% url 'blog:post_share' post.id %}">
        Share
    </a>
    {% if user.is_authenticated %}
    {% if request.user.id == post.author.id %}

    <a class="activities-bar-item" href="{% url 'blog:post_edit' post.slug  %}">
        Edit
    </a>
    <a class="activities-bar-item" href="{% url 'blog:post_del' post.slug  %}">
        Delete
    </a>
    {% endif %}
    {% endif %}
</div>

<div class="similar-posts-container">
    <h2 class="similar-posts-title">Similar posts</h2>
    {% for post in similar_posts %}
    <div class="similar-posts-item">
        <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
    </div>
    {% empty %}
    There are no similar posts yet.
    {% endfor %}
</div>

<div class="comments-container">
    {% with comments.count as total_comments %}
    <h2 class="comments-header">
        {{ total_comments }} comment{{ total_comments|pluralize }}
    </h2>
    {% endwith %}

    <br />

    {% for comment in comments %}
    <div class="comment">
        <p class="info">
            {{ comment.name }} -
            {{ comment.created }}
        </p>
        {{ comment.body|linebreaks }}
    </div>
    {% empty %}
    <p>There are no comments yet.</p>
    {% endfor %}
</div>

<div class="new-comment-container">
    {% if new_comment %}
    <h2 class="new-comment">Your comment has been added.</h2>
    {% else %}
    <h2 class="new-comment-form">Add a new comment</h2>
    <form method="post">
        {{ comment_form|crispy }}
        {% csrf_token %}
        <p><input class="new-comment-submit-btn" type="submit" value="Add comment"></p>
    </form>
    {% endif %}
</div>

{% endblock %}

templates/blog/templates/blog/post/latest_posts.html
<ul class="sidebar-list-container">
    {% for post in latest_posts %}
    <li>
        <a class="sidebar-list" href="{{ post.get_absolute_url }}">{{ post.title }}</a>
    </li>
    {% endfor %}
</ul>

templates/blog/templates/blog/post/list.html
{% extends "blog/base.html" %}
{% load blog_tags %}
{% load urlify %}

{% block title %}Your Blog{% endblock %}

{% block content %}
{% if tag %}
<h2 class="blog-post-title">Posts tagged with "{{ tag.name }}"</h2>
{% endif %}

{% for post in posts %}
<div class="blog-post-container">
    <div class="list-profile-img-container">
        <a href="{% url 'profile' post.author.profile.name %}">
            <img class="list-profile-img" src="{{ post.author.profile.picture.url }}" />
        </a>
    </div>
    <div class="blog-post-content">
        <p class="date">
            <span class="blog-post-author"><a href="{% url 'profile' post.author.profile.name %}">{{ post.author }}</a></span>{{ post.publish }}
        </p>
        <h2 class="blog-post-title">
            <a href="{{ post.get_absolute_url }}">
                {{ post.title }}
            </a>
            <div class="text-muted tag-container">
            {% for tag in post.tags.all %}
                    <a class="tags" href="{% url 'blog:post_list_by_tag' tag.slug %}">
                        {{ tag.name }}
                    </a>
            {% endfor %}
            </div>
        </h2>

        {% if post.image %}
        <img class="imgr" src='{{ post.image.url }}' />
        {% endif %}
        <div class="blog-body">{{ post.body|markdown|truncatewords_html:20 }}</div>
    </div>
</div>
{% endfor %}


{% include "pagination.html" with page=posts %}

{% endblock %}

templates/blog/templates/blog/post/post_form.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}




{% block content %}
 
<form method="POST"  action="" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.media }}
    {{ form|crispy }}
    <input type="submit">
</form>

{% endblock %}

templates/blog/templates/blog/post/postdelete.html
{% extends "blog/base.html" %}


{% block content %}
<form method="POST">
    {% csrf_token %}
    <p>Are u sure. Want to delete "{{object}}"</p>

    <a href="{{object.get_absolute_url}} ">Go back</a>
    <input type="submit" value="confirm">
</form>
{% endblock %}

templates/blog/templates/blog/post/search.html
{% extends "blog/base.html" %}
{% load blog_tags %}

{% block content_search %}
{% if searched %}
<h2 class="search-header">You searched for ... {{ searched }}</h2>

{% for p in result %}
<div class="search-container">
    <div class="search-post-title">
        <a href="{{ p.get_absolute_url }}">
            {{ p.title }}
        </a>
    </div>
    <div class="search-post-body">
        {{ p.body|markdown|truncatewords_html:20 }}
    </div>
</div>
{% endfor %}
{% if not result %}
<h2 class="search-header">Nothing Found...</h2>
{% endif %}
{% endif %}
{% endblock %}

templates/blog/templates/blog/post/share.html
{% extends "blog/base.html" %}
{% block title %}Share a post{% endblock %}
{% block content %}
{% if sent %}
<h1>E-mail successfully sent</h1>
<p>
    "{{ post.title }}" was successfully sent to "{{ form.cleaned_data.to }}".
</p>
{% else %}
<h1>Share "{{ post.title }}" by e-mail</h1>
<form method="post">
    {{ form.as_p }}
    {% csrf_token %}
    <input type="submit" value="Send e-mail">
</form>
{% endif %}
{% endblock %}