blog/urls.py
from unicodedata import name
from django.urls import path
from . import views


app_name = 'blog'
urlpatterns = [
    # post views  
    path('', views.post_list, name='post_list'),
    path('q/', views.search_post, name='search_post'),
    path('new/', views.post_create, name='post_create'),
    path('<slug:post>/edit/', views.post_edit, name='post_edit'),
    path('<slug:post>/',views.post_detail, name='post_detail'),
    path('<slug:post>/del/',views.deletePost, name='post_del'),
    path('<int:post_id>/share/',views.post_share, name='post_share'),
    path('tag/<slug:tag_slug>/',views.post_list, name='post_list_by_tag'),
    path('<slug:post>/like',views.like_view,name='like_post'),
    

]

blogForum/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('', include('accounts.urls')),
    path('b/', include('blog.urls')),
    path('ask/', include('forum.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
]


if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

forum/urls.py
from django.urls import path
from . import views

app_name = 'forum'
urlpatterns=[
    path('',views.home,name='home'),
    path('tags',views.tags,name='tags'),
    path('tag/<str:tag>/',views.tag,name='tag'),
    path('ask-question',views.ask_form,name='ask-question'),
    path('unanswered',views.give_answer,name='unanswered'),
    path('save-comment',views.save_comment,name='save-comment'),
    path('<int:pk>/ans_edit/', views.answer_edit, name='ans_edit'),
    path('<int:pk>/ans_del/',views.deleteAns, name='ans_del'),
    path('<slug:slug>',views.detail,name='detail'),
    path('<slug:slug>/edit/', views.post_edit, name='ques_edit'),
    path('<slug:slug>/del/',views.deletePost, name='ques_del'),
    path('<int:id>/<int:pk>/save-upvote',views.save_upvote,name='save-upvote'),
    path('<int:id>/<int:pk>/save-downvote',views.save_downvote,name='save-downvote'),
    
    
    
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager
from django.utils.text import slugify
from django.db.models.signals import pre_save
from ckeditor.fields import RichTextField
# Create your models here.


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset()\
            .filter(status='published')


class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = models.CharField(max_length=250)
    # slug = models.SlugField(max_length=250, unique_for_date='publish')
    slug = models.SlugField(unique=True)
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='blog_posts')
    # body = models.TextField()
    body=RichTextField(blank=True,null=True)
    image=models.ImageField(null=True,blank=True,upload_to='blog_post')
    # height_field = models.IntegerField(default=0)
    # width_field = models.IntegerField(default=0)
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(
        max_length=10, choices=STATUS_CHOICES, default='published')
    likes=models.ManyToManyField(User,related_name='like_post')
    tags = TaggableManager(blank=True)


    objects = models.Manager()
    published = PublishedManager()

    def total_likes(self):
        return self.likes.count()

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.slug])

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey(Post,on_delete=models.CASCADE,related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)
    class Meta:
        ordering = ('created',)
    def __str__(self):
        return f'Comment by {self.name} on {self.post}'

 

from .utils import unique_slug_generator

def pre_save_post_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        # instance.slug = create_slug(instance)
        instance.slug = unique_slug_generator(instance)



pre_save.connect(pre_save_post_receiver, sender=Post)

blog/forms.py
from django import forms
from .models import Comment, Post
from taggit.forms import TagWidget
# from pagedown.widgets import PagedownWidget

class PostForm(forms.ModelForm):
    # body = forms.CharField(widget=PagedownWidget())
    class Meta:
        model=Post
        fields=['title','body','image','tags']
        widgets = {
            'tags': TagWidget(),
             
        }
        labels={
            'body':'',
        }


class EmailPostForm(forms.Form):
    # name = forms.CharField(max_length=25)
    # email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['body']
    

    

blog/views.py
from email import message
from importlib.resources import contents
from re import search
from django.contrib import messages
from multiprocessing import context
from urllib import request
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from .models import Post, Comment
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .forms import EmailPostForm, CommentForm, PostForm
from django.core.mail import send_mail
from taggit.models import Tag
from django.db.models import Count
import os
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from django.db.models import Q

# Create your views here.

def search_post(request):
    query=request.GET.get("q")
    result=None
    lookups=Q(title__icontains=query) | Q(body__icontains=query)
    result=Post.objects.filter(lookups)
    content={
        "searched":query,
        "result":result
    }
    return render(request,'blog/post/search.html',content)
    


@login_required
def like_view(request,post):
    p=get_object_or_404(Post,slug=post,status='published')
    liked=False
    if p.likes.filter(id=request.user.id).exists():
        p.likes.remove(request.user)
        liked=False
    else:
        p.likes.add(request.user)
        liked=True

    return redirect(p.get_absolute_url())

@login_required
def post_create(request):
    form = PostForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.author = request.user
        instance.save()
        form.save_m2m()
      
        messages.success(request, "Successfully Created")
        return redirect(instance.get_absolute_url())
    context = {
        "form": form,
        'page': 'new-post',
      
    }
    return render(request, "blog/post/post_form.html", context)


@login_required
def post_edit(request, post):

    page = 'post-edit'
    p = get_object_or_404(Post, slug=post, status='published')
    if p.author.id != request.user.id:
        raise PermissionDenied
    form = PostForm(instance=p)

    if request.method == 'POST':
        form = PostForm(request.POST,
                        request.FILES,
                        instance=p)
        if form.is_valid():
            form.save()
            print(p.tags.all())
            messages.success(request, f'Post Updated')
            return redirect(p.get_absolute_url())

    else:
        form = PostForm(instance=p)

    context = {
        'form': form,
        'page': page,
        'post': p,
    }

    return render(request, 'blog/post/detail.html', context)


@login_required
def deletePost(request, post):
    # p=Post.objects.get(slug=slug)

    p = get_object_or_404(Post, slug=post, status='published')
    if p.author.id != request.user.id:
        raise PermissionDenied

    if request.method == 'POST':
        p.delete()
        return redirect('blog:post_list')

    context = {'object': p}
    return render(request, 'blog/post/postdelete.html', context)


def post_list(request, tag_slug=None):
    object_list = Post.published.all()
    tag = None

    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])

    paginator = Paginator(object_list, 8)  # 3 posts in each page
    page = request.GET.get('page')

    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        posts = paginator.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        posts = paginator.page(paginator.num_pages)

    # posts = Post.published.all()
    context = {
        'posts': posts,
        'page': page,
        'tag': tag
    }
    return render(request, 'blog/post/list.html', context)

@login_required
def post_detail(request,  post):
    post = get_object_or_404(Post, slug=post,
                             status='published',
                             )
    # List of active comments for this post
    comments = post.comments.filter(active=True)

    new_comment = None

    if request.method == 'POST':
        # A comment was posted
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.name=request.user
           
        # # Create Comment object but don't save to database yet
            new_comment.post = post
        # Assign the current post to the comment
            new_comment.save()
        # Save the comment to the database
            return redirect(post.get_absolute_url())

    else:
        comment_form = CommentForm()

    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(
        tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags'))\
        .order_by('-same_tags', '-publish')[:4]

    total_likes=post.total_likes()
    
    liked=False
    if post.likes.filter(id=request.user.id).exists():
        liked=True
   
    
    

    context = { 
        'post': post,
        'comments': comments,
        'new_comment': new_comment,
        'comment_form': comment_form,
        'similar_posts': similar_posts,
        'total_likes':total_likes,
        'liked':liked
    }

    return render(request, 'blog/post/detail.html', context)


@login_required
def post_share(request, post_id):
    # Retrive post by id
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False

    if request.method == 'POST':
        form = EmailPostForm(request.POST)
        if form.is_valid():
            # Form feilds passsed validation.
            cd = form.cleaned_data
            # send mail
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = f"{ request.user } recommends you read {post.title}"
            message = f"Read {post.title} at {post_url}\n\n" \
                      f"{request.user}\'s comments: {cd['comments']}"
            send_mail(subject, message, os.environ.get(
                'EMAIL_USER'), [cd['to']])
            sent = True

    else:
        form = EmailPostForm()
    context = {
        'post': post,
        'form': form,
        'sent': sent
    }

    return render(request, 'blog/post/share.html', context)

templates/blog/templates/blog/base.html
{% load blog_tags %}
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <title>
        {% block title %}
        {% endblock %}
    </title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel='stylesheet' type="text/css" media="screen" href="{% static 'css/blog.css' %}?{% now 'U' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    {% block head_extra %}
    {% endblock %}

</head>

<body>
    <div id="id-sidebar" class="sidebar">
        <button onclick="cus_close()" class="close-btn sidebar-para">&#10006;</button>
        <div class="sidebar-container">
            <h2 class="sidebar-title">Your blog</h2>
            <p class="sidebar-para">You've written {% total_posts %} posts so far.</p>
            <h3 class="sidebar-subtitle">Latest posts</h3>
            {% show_latest_posts 5 %}

            <h3 class="sidebar-subtitle">Most commented posts</h3>
            {% get_most_commented_posts as most_commented_posts %}
            <ul class="sidebar-list-container">
                {% for post in most_commented_posts %}
                <li>
                    <a class="sidebar-list" href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>
    <div class="blog-container">

        <nav class="blog-nav">
            <button onclick="cus_open()" class="open-btn blog-float-left">☰</button>
            <a class="blog-float-left" href="{% url 'index' %}"><i class="fa fa-home" aria-hidden="true"></i></a>
            <a class="blog-float-left" href="{% url 'blog:post_list' %}">Blog</a>
            <a class="blog-float-left" href="{% url 'forum:home' %}">Forum</a>
            {% if user.is_authenticated %}
            <a class="blog-float-right" href="{% url 'account_logout' %}"><i class="fa fa-sign-out"
                    aria-hidden="true"></i></a>
            <a class="blog-float-right" href="{% url 'profile' request.user.profile.name %}"><i class="fa fa-user"
                    aria-hidden="true"></i></a>
            {% if page != 'new-post' %}
            <a class="blog-float-right" href="{% url 'blog:post_create' %}"><i class="fa fa-solid fa-plus"></i></a>
            {% endif %}
            {% else %}
            <a class="blog-float-right" href="{% url 'account_login' %}">Login</a>
            <a class="blog-float-right" href="{% url 'account_signup' %}">Sign Up</a>
            {% endif %}
        </nav>

        <div class="container">

            {% if messages %}
            {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">
                {{ message }}
            </div>
            {% endfor %}
            {% endif %}

        </div>

        <form class="input-group padded" action="{% url 'blog:search_post' %}" method='GET'>
            <input type="search" class="form-control rounded" placeholder="Search" aria-label="Search"
                aria-describedby="search-addon" name="q" />
            <button class="btn btn-outline-secondary" type="submit">search</button>
        </form>

        <div class="content">
            {% block content_search %}
            {% endblock %}
            {% block content %}
            {% endblock %}
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
    <script src="{% static 'js/blog.js' %}"></script>


</body>

</html>