blog/urls.py
from unicodedata import name
from django.urls import path
from . import views


app_name = 'blog'
urlpatterns = [
    # post views  
    path('', views.post_list, name='post_list'),
    path('q/', views.search_post, name='search_post'),
    path('new/', views.post_create, name='post_create'),
    path('<slug:post>/edit/', views.post_edit, name='post_edit'),
    path('<slug:post>/',views.post_detail, name='post_detail'),
    path('<slug:post>/del/',views.deletePost, name='post_del'),
    path('<int:post_id>/share/',views.post_share, name='post_share'),
    path('tag/<slug:tag_slug>/',views.post_list, name='post_list_by_tag'),
    path('<slug:post>/like',views.like_view,name='like_post'),
    

]

blogForum/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('', include('accounts.urls')),
    path('b/', include('blog.urls')),
    path('ask/', include('forum.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
]


if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

forum/urls.py
from django.urls import path
from . import views

app_name = 'forum'
urlpatterns=[
    path('',views.home,name='home'),
    path('tags',views.tags,name='tags'),
    path('tag/<str:tag>/',views.tag,name='tag'),
    path('ask-question',views.ask_form,name='ask-question'),
    path('unanswered',views.give_answer,name='unanswered'),
    path('save-comment',views.save_comment,name='save-comment'),
    path('<int:pk>/ans_edit/', views.answer_edit, name='ans_edit'),
    path('<int:pk>/ans_del/',views.deleteAns, name='ans_del'),
    path('<slug:slug>',views.detail,name='detail'),
    path('<slug:slug>/edit/', views.post_edit, name='ques_edit'),
    path('<slug:slug>/del/',views.deletePost, name='ques_del'),
    path('<int:id>/<int:pk>/save-upvote',views.save_upvote,name='save-upvote'),
    path('<int:id>/<int:pk>/save-downvote',views.save_downvote,name='save-downvote'),
    
    
    
]

forum/models.py
from django.db import models
from django.contrib.auth.models import User,AbstractUser
from django.db.models.signals import pre_save
from django.utils.text import slugify
from django.urls import reverse
from ckeditor.fields import RichTextField
# Create your models here.

class Question(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    title=models.CharField(max_length=300)
    slug = models.SlugField(unique=True)
    detail=RichTextField()
    tags=models.TextField(default='')
    add_time=models.DateTimeField(auto_now_add=True)

    def get_absolute_url(self):
        return reverse('forum:detail', args=[self.slug])

    def __str__(self):
        return self.title

    
class Answer(models.Model):
    question=models.ForeignKey(Question,on_delete=models.CASCADE)
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    detail=RichTextField()
    add_time=models.DateTimeField(auto_now_add=True)
    upvote=models.ManyToManyField(User,related_name='upvote_ans')
    downvote=models.ManyToManyField(User,related_name='downvote_ans')
    total_upvote=models.IntegerField(default=0)
    total_downvote=models.IntegerField(default=0)

    def __str__(self):
        return self.detail

class Comment(models.Model):
    answer=models.ForeignKey(Answer,on_delete=models.CASCADE)
    user=models.ForeignKey(User,on_delete=models.CASCADE,related_name='comment_user')
    comment=models.TextField(default='')
    add_time=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.comment






from blog.utils import unique_slug_generator

def pre_save_post_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        # instance.slug = create_slug(instance)
        instance.slug = unique_slug_generator(instance)



pre_save.connect(pre_save_post_receiver, sender=Question)

forum/forms.py
from django.forms import ModelForm
from .models import Answer,Question 

class AnswerForm(ModelForm):
    class Meta:
        model=Answer
        fields=('detail',)

class QuestionForm(ModelForm):
    class Meta:
        model=Question
        fields=('title','detail','tags')

 

forum/views.py
from multiprocessing import context
from django.shortcuts import render,HttpResponse,get_object_or_404,redirect
from django.http import JsonResponse,HttpResponseRedirect
from .models import Question,Answer,Comment
from django.core.paginator import Paginator
from django.contrib import messages
from .forms import AnswerForm,QuestionForm
from django.db.models import Count
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied


# Home Page
def home(request):
    page='home'
    if 'q' in request.GET:
        q=request.GET['q']
        quests=Question.objects.annotate(total_comments=Count('answer__comment')).filter(title__icontains=q).order_by('-id')
    else:
        quests=Question.objects.annotate(total_comments=Count('answer__comment')).all().order_by('-id')
    paginator=Paginator(quests,10)
    page_num=request.GET.get('page',1)
    quests=paginator.page(page_num)
    context={
        'quests':quests,
        'page':page,
    }
    return render(request,'forum/home.html',context)

def give_answer(request):
    if 'q' in request.GET:
        q=request.GET['q']
        unanswered_question=Question.objects.filter(answer__isnull=True).filter(title__icontains=q)
    else:
        unanswered_question=Question.objects.filter(answer__isnull=True)
    count=unanswered_question.count()
    
    paginator=Paginator(unanswered_question,17)
    page_num=request.GET.get('page',1)
    unanswered_question=paginator.page(page_num)
    
    context={
        'unanswered_question':unanswered_question,
        'count':count,
    }
    return render(request,'forum/unanswered.html',context)

# Detail
@login_required
def detail(request,slug):
    quest=get_object_or_404(Question,slug=slug)
    tags=quest.tags.split(',')
    answers=Answer.objects.filter(question=quest)
    answerform=AnswerForm
    if request.method=='POST':
        answerData=AnswerForm(request.POST)
        if answerData.is_valid():
            answer=answerData.save(commit=False)
            answer.question=quest
            answer.user=request.user
            answer.save()
            messages.success(request,'Answer has been submitted.')
    context={
        'quest':quest,
        'tags':tags,
        'answers':answers,
        'answerform':answerform
    }
    return render(request,'forum/detail.html',context)

# Save Comment
@login_required
def save_comment(request):
    if request.method=='POST':
        comment=request.POST['comment']
        answerid=request.POST['answerid']
        answer=Answer.objects.get(pk=answerid)
        user=request.user
        Comment.objects.create(
            answer=answer,
            comment=comment,
            user=user
        )
        return JsonResponse({'bool':True})

 
@login_required
def save_upvote(request,id,pk):
    p=get_object_or_404(Answer,id=id)

    if p.downvote.filter(id=request.user.id).exists():
        p.downvote.remove(request.user)

    if p.upvote.filter(id=request.user.id).exists():
        p.upvote.remove(request.user)
    else:
        p.upvote.add(request.user)

    p.total_upvote=p.upvote.count()
    p.total_downvote=p.downvote.count()
    p.save()

    q=get_object_or_404(Question,id=pk)

    return redirect(q.get_absolute_url())  

@login_required
def save_downvote(request,id,pk):
    p=get_object_or_404(Answer,id=id)

    if p.upvote.filter(id=request.user.id).exists():
        p.upvote.remove(request.user)

    if p.downvote.filter(id=request.user.id).exists():
        p.downvote.remove(request.user)
    else:
        p.downvote.add(request.user)

    p.total_upvote=p.upvote.count()
    p.total_downvote=p.downvote.count()
    p.save()

    q=get_object_or_404(Question,id=pk)  
    return redirect(q.get_absolute_url()) 


# Ask Form
@login_required
def ask_form(request):
    form=QuestionForm
    if request.method=='POST':
        questForm=QuestionForm(request.POST)
        if questForm.is_valid():
            questForm=questForm.save(commit=False)
            questForm.user=request.user
            questForm.save()
            messages.success(request,'Question has been added.')
            return redirect(questForm.get_absolute_url())
    return render(request,'forum/ask-question.html',{'form':form})



@login_required
def answer_edit(request, pk):
    pg = 'answer-post'
    p = get_object_or_404(Answer,id=pk)
    if p.user.id != request.user.id:
        raise PermissionDenied
    ans_form = AnswerForm(instance=p)

    if request.method == 'POST':
        ans_form =AnswerForm(request.POST,
                        request.FILES,
                        instance=p)
        if ans_form.is_valid():
            ans_form.save()
            messages.success(request, f'Answer Updated')
            return redirect(p.question.get_absolute_url())
    else:
        ans_form = AnswerForm(instance=p)
    print("OK")
    print(ans_form)

    context = {
        'ans_form': ans_form,
        'pg': pg,
        'post': p,
    }
    return render(request, 'forum/ansedit.html', context)


@login_required
def deleteAns(request, pk):
    p = get_object_or_404(Answer,id=pk)
    if p.user.id != request.user.id:
        raise PermissionDenied

    if request.method == 'POST':
        p.delete()
        return redirect(p.question.get_absolute_url())

    context = {'object': p}
    return render(request, 'forum/ansdelete.html', context)



@login_required
def post_edit(request, slug):

    page = 'post-edit'
    p = get_object_or_404(Question, slug=slug)
    if p.user.id != request.user.id:
        raise PermissionDenied
    form = QuestionForm(instance=p)

    if request.method == 'POST':
        form = QuestionForm(request.POST,
                        request.FILES,
                        instance=p)
        if form.is_valid():
            form.save()
            messages.success(request, f'Question Updated')
            return redirect(p.get_absolute_url())

    else:
        form = QuestionForm(instance=p)

    context = {
        'form': form,
        'page': page,
        'post': p,
    }

    return render(request, 'forum/detail.html', context)


@login_required
def deletePost(request, slug):
    # p=Post.objects.get(slug=slug)

    p = get_object_or_404(Question, slug=slug)
    if p.user.id != request.user.id:
        raise PermissionDenied

    if request.method == 'POST':
        p.delete()
        return redirect('forum:home')

    context = {'object': p}
    return render(request, 'forum/quesdelete.html', context)




# Questions according to tag
def tag(request,tag):
    quests=Question.objects.annotate(total_comments=Count('answer__comment')).filter(tags__icontains=tag).order_by('-id')
    paginator=Paginator(quests,10)
    page_num=request.GET.get('page',1)
    quests=paginator.page(page_num)
    return render(request,'forum/tag.html',{'quests':quests,'tag':tag})



# Tags Page
def tags(request):
    quests=Question.objects.all()
    tags=[]
    for quest in quests:
        qtags=[tag.strip() for tag in quest.tags.split(',')]
        for tag in qtags:
            if tag not in tags:
                tags.append(tag)
    # Fetch Questions
    tag_with_count=[]
    for tag in tags:
        tag_data={
            'name':tag,
            'count':Question.objects.filter(tags__icontains=tag).count()
        }
        tag_with_count.append(tag_data)
    print(tag_with_count)
    return render(request,'forum/tags.html',{'tags':tag_with_count})
        
        

templates/forum/ansdelete.html
{% extends "forum/base.html" %}


{% block content %}
<center style="margin-top: 10%">
    <form method="POST">
        {% csrf_token %}
        <h5>Are u sure. Want to delete your answer ?</h5>
        <div style=" width: 320px; padding: 10px;  border: 1px solid rgb(128, 128, 128); margin: 0;">
            <p>"{{object|safe}}"</p>
        </div>
        <div style="margin-top: 25px;"></div>
        <a href="{{ request.META.HTTP_REFERER }}" class="btn btn-warning">Go back</a>
        <input type="submit" value="confirm" class="btn btn-danger">
    </form>
</center>

{% endblock %}

templates/forum/ansedit.html
{% extends "forum/base.html" %}


{% block content %}

<div class="container">
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Edit your answer</legend>
            {{ ans_form.media }}
            {{ ans_form.as_p}}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit">Update</button>
        </div>
    </form>
</div>

{% endblock %}

templates/forum/ask-question.html
{% extends 'forum/base.html' %}
{% load crispy_forms_tags %}
{% block title %}Ask Question{% endblock %}
{% block content %}
<div class="container">
    <div class="card mt-5">
        <h5 class="card-header">Ask Question</h5>
        <div class="card-body">
            {% for msg in messages %}
            <p class="text-success">{{msg}}</p>
            {% endfor %}
            <form method="post">
                {% csrf_token %}
                {{form.media}}
                {{form.as_p}}
                <button class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/forum/detail.html
{% extends 'forum/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% load humanize %}
{% block title %}{{quest.title}}{% endblock %}
{% block content %}
<!-- Question List -->
<div class="container">
    {% if pg != 'answer-post' %}
    {% if page != 'post-edit' %}
    <h2 class="my-4">{{quest.title}}</h2>
        <div class="btn-group">
                {% if user.is_authenticated %}
                {% if request.user.id == quest.user.id %}
                    <a href="{% url 'forum:ques_edit' quest.slug  %}">
                        <button type="button" class="btn btn-outline-warning">Edit</button>
                    </a>
                    <br>
                    <a href="{% url 'forum:ques_del' quest.slug  %}">
                        <button type="button" class="btn btn-danger">Delete</button>
                    </a>
                {% endif %}
                {% endif %}
        </div>
        <p>{{quest.detail|safe }}</p>
        <p>
            tags:
            {% for tag in tags %}
            <a href="/ask/tag/{{tag|slugify}}" class="badge badge-secondary p-1">{{tag}}</a>
            {% endfor %}
        </p>
        {% if user.is_authenticated %}
            <p>
                <span class="mr-4">{{quest.add_time|date:'d/m/Y'}}</span>
                <a href="{% url 'profile' quest.user.profile.name %}">{{quest.user.username}}</a>
            </p>
        {% endif %}
    <hr/>
     
    {% endif %}

    {% if page == 'post-edit' %}
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Edit your post</legend>
                {{ form.media }}
                {{ form.as_p}}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Update</button>
            </div>
        </form>
    {% endif %}

    {% endif %}

   
    {% for answer in answers %}
    
    <div class="row">
        <div class="col-1" style="text-align: center;">

            <div class="upvote">
                <strong>{{answer.total_upvote}}</strong><br />
                <span class="text-success">
                    <form method="POST" action="{% url 'forum:save-upvote' answer.id quest.id %}">
                        {% csrf_token %}
                        <button type="submit" ,name='answer_id' ,value='{{ answer.id }}'>
                            <i class="fa fa-arrow-up fa-2x"></i>
                        </button>
                    </form>
                </span>
            </div>
            <div class="downvote mt-3">
                <span class="text-danger">
                    <form method="POST" action="{% url 'forum:save-downvote' answer.id quest.id %}">
                        {% csrf_token %}
                        <button type="submit" ,name='answer_id' ,value='{{ answer.id }}'>
                            <i class="fa fa-arrow-down fa-2x"></i>
                        </button>
                    </form>
                </span><br />
                <strong>{{answer.total_downvote}}</strong>
            </div>

        </div>

        <div class="col-11">
            {% if page != 'post-edit' %}
            {% if pg != 'answer-post' %}
            <p>
                {{ answer.detail|safe }}
            </p>

            <p>
                <a href="{% url 'profile' answer.user.profile.name %}" class="mr-3">{{answer.user.username}}</a>
                <span class="mr-3"><span class="comment-count-{{answer.id}}">{{answer.comment_set.count}}</span>
                    comments</span>
                <span>{{answer.add_time|date:'d/m/Y h:i:s'}}</span>
                {% if user.is_authenticated %}
                {% if request.user.id == answer.user.id %}
                <div class="btn-group">
                    <a href="{% url 'forum:ans_edit' answer.id  %}">
                        <button type="button" >
                            <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                        </button>
                    </a>
                    <br>
                    <a href="{% url 'forum:ans_del' answer.id  %}">
                        <button type="button">
                            <i class="fa fa-trash-o" aria-hidden="true"></i>
                        </button>
                    </a>
                </div>
                {% endif %}
                {% endif %}
            </p>
            {% endif %}
            {% endif %}

            <!-- Comment Section Start -->
            <h3 class="my-4">Comment</h3>
            <div class="comment-wrapper-{{answer.id}}">
                {% for comment in answer.comment_set.all %}
                <div class="card mb-2">
                    <div class="card-body">
                        <p>{{comment.comment}}</p>
                        <p>
                            <a href="{% url 'profile' comment.user.profile.name %}">{{comment.user.username}}</a>
                        </p>
                    </div>
                </div>
                {% endfor %}
            </div>

            <!-- Comment Form -->
            <div class="card my-3">
                <h6 class="card-header">Add Comment</h6>
                <div class="card-body">
                    <textarea class="form-control comment-text-{{answer.id}}"></textarea>
                    <button type="button" data-answer="{{answer.id}}"
                        class="btn btn-dark my-3 save-comment">Submit</button>
                </div>
            </div>

        </div>
    </div>
    <hr />
    {% endfor %}

    {% if user.is_authenticated %}
    {% for msg in messages %}
    <p class="text-success">{{msg}}</p>
    {% endfor %}
    {% if page != 'post-edit' %}
    {% if pg != 'answer-post' %}
        <form method="post">
            {% csrf_token %}
            <table class="table table-bordered">
                {{answerform.media}}
                {{answerform|crispy}}
                <tr>
                    <td colspan="2">
                        <input type="submit" class="btn btn-dark" />
                    </td>
                </tr>
            </table>
        </form>
    {% endif %}
    {% endif %}
    {% endif %}
</div>
<script>
    $(document).ready(function () {
        $(".save-comment").on('click', function () {
            var _answerid = $(this).data('answer');
            var _comment = $(".comment-text-" + _answerid).val();
            // Ajax
            $.ajax({
                url: "/ask/save-comment",
                type: "post",
                data: {
                    comment: _comment,
                    answerid: _answerid,
                    csrfmiddlewaretoken: "{{csrf_token}}"
                },
                dataType: 'json',
                beforeSend: function () {
                    $(".save-comment").addClass('disabled').text('saving...');
                },
                success: function (res) {
                    if (res.bool == true) {
                        $(".comment-text-" + _answerid).val('');
                        // Append Element
                        var _html = '<div class="card mb-2 animate__animated animate__bounce">\
                        <div class="card-body">\
                            <p>'+ _comment + '</p>\
                            <p>\
                                <a href="#">{{request.user}}</a>\
                            </p>\
                        </div>\
                    </div>';
                        $(".comment-wrapper-" + _answerid).append(_html);
                        var prevCount = $(".comment-count-" + _answerid).text();
                        $(".comment-count-" + _answerid).text(parseInt(prevCount) + 1);
                    }
                    $(".save-comment").removeClass('disabled').text('Submit');
                }
            });
        });

        // Upvote
        $(".upvote-click").on('click', function () {
            var answerid = $(this).data('answer');
            // Ajax
            $.ajax({
                url: "/ask/save-upvote",
                type: "post",
                data: {
                    answerid: answerid,
                    csrfmiddlewaretoken: "{{csrf_token}}"
                },
                dataType: 'json',
                success: function (res) {
                    var _prevupvote = $(".upvote-count-" + answerid).text();
                    if (res.bool == true) {
                        $(".upvote-count-" + answerid).text(parseInt(_prevupvote) + 1);
                    }
                }
            });
        });

        // Downvote
        $(".downvote-click").on('click', function () {
            var answerid = $(this).data('answer');
            // Ajax
            $.ajax({
                url: "/ask/save-downvote",
                type: "post",
                data: {
                    answerid: answerid,
                    csrfmiddlewaretoken: "{{csrf_token}}"
                },
                dataType: 'json',
                success: function (res) {
                    var _prevupvote = $(".downvote-count-" + answerid).text();
                    if (res.bool == true) {
                        $(".downvote-count-" + answerid).text(parseInt(_prevupvote) + 1);
                    }
                }
            });
        });
    });
</script>
{% endblock %}

templates/forum/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Forum</title>
   
    <link rel="stylesheet" href="{% static 'fa4/css/font-awesome.min.css' %}" />
    <!-- Custom CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/forum.css' %}?{% now 'U' %}" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

</head>
<body>
     {% include 'forum/navbar.html' %}
    <div class="container py-5">
        <div class="row">
            <div class="col-md-8 offset-2">
                <form>
                    <div class="input-group">
                        <input type="text" name="q" class="form-control form-control-lg" placeholder="Search" />
                        <div class="input-group-append">
                        <button class="btn btn-dark btn-lg" type="submit" id="button-addon2">Search</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
  

    

    <div class="container">
        {% for quest in quests %}
        <div class="card mb-4 shadow">
            <div class="card-body">
                <h4 class="card-title"><a href="{% url 'forum:detail' quest.slug %}">{{quest.title}}</a></h4>
                <p class="card-text">{{quest.detail|safe}}</p>
                <p>
                    {% if user.is_authenticated %}
                    <a href="{% url 'profile' quest.user.profile.name %}" class="mr-2">{{quest.user.username}}</a>
                    <a href="#" class="mr-2">{{quest.answer_set.count}} Answers</a>
                    <a href="#" class="mr-2">{{quest.total_comments}} Comments</a>
                    {% endif %}
                </p>
            </div>
            <div class="card-footer">
                <small>{{quest.add_time}}</small>
            </div>
        </div>
        {% endfor %}
    </div>
    {% if quests.has_other_pages %}
    <!-- Pagination -->
    <nav class="my-3 container">
        <ul class="pagination">
            {% if quests.has_previous %}
          <li class="page-item"><a class="page-link" href="?page={{quests.previous_page_number}}">Previous</a></li>
          {% endif %}
          {% for i in quests.paginator.page_range %}
          {% if quests.number == i %}
          <li class="page-item active"><a class="page-link" href="#">{{i}}</a></li>
          {% else %}
          <li class="page-item"><a class="page-link" href="?page={{i}}">{{i}}</a></li>
          {% endif %}
          {% endfor %}
          {% if quests.has_next %}
          <li class="page-item"><a class="page-link" href="?page={{quests.next_page_number}}">Next</a></li>
          {% endif %}
        </ul>
      </nav>
    {% endif %}

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</body>
</html>

templates/forum/navbar.html
<nav  class="navbar navbar-light" style="background-color: #82dadd">
    <div class="container">
        <a class="navbar-brand" href="/"><strong>Home</strong></a>

        <nav class="nav nav-pills nav-justified">
            <a class="nav-item nav-link" style="color: black;" href="{% url 'blog:post_list' %}"><strong>BLOG</strong></a>
            <a class="nav-item nav-link"style="color: black;"  href="{% url 'forum:home' %}"><strong>FORUM</strong></a>
            {% if page == 'home' %}
            <a class="nav-item nav-link"style="color: black;"  href="{% url 'forum:ask-question' %}"><i class="fa fa-question-circle"></i></a>
            <a class="nav-item nav-link"style="color: black;"  href="{% url 'forum:unanswered' %}">Help<i class="fa-solid fa-comment-question"></i></a>
            {% endif %}
        </nav> 

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'forum:tags' %}">Tags</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'forum:ask-question' %}">Ask</a>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'profile' request.user.profile.name %}">Profile</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'account_logout' %}">Logout</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'account_login' %}">Login</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'account_signup' %}">Register</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

templates/forum/quesdelete.html
{% extends "forum/base.html" %}


{% block content %}
<center style="margin-top: 10%">
    <form method="POST">
        {% csrf_token %}
        <h5>Are u sure. Want to delete ?</h5>
        <div style=" width: 320px; padding: 10px;  border: 1px solid rgb(128, 128, 128); margin: 0;">
            <p>"{{object}}"</p>
        </div>
        <div style="margin-top: 25px;"></div>
        <a href="{{object.get_absolute_url}} " class="btn btn-warning">Go back</a>
        <input type="submit" value="confirm" class="btn btn-danger">
    </form>
</center>

{% endblock %}

templates/forum/tag.html
{% extends 'forum/base.html' %}
{% load static %}
{% load humanize %}
{% block title %}{{tag}}{% endblock %}
{% block content %}
    <!-- Question List -->
    <div class="container py-5">
        {% for quest in quests %}
        <div class="card mb-3">
            <div class="card-body">
                <h4 class="card-title"><a href="{% url 'forum:detail' quest.slug %}">{{quest.title}}</a></h4>
                <p class="card-text">{{quest.detail|safe}}</p>
                <p>
                    <a href="{% url 'profile' request.user.profile.name %}" class="mr-2">{{quest.user.username}}</a>
                    <a href="#" class="mr-2">{{quest.answer_set.count}} Answers</a>
                    <a href="#" class="mr-2">{{quest.total_comments}} Comments</a>
                </p>
            </div>
        </div>
        {% endfor %}
    </div>
    {% if quests.has_other_pages %}
    <!-- Pagination -->
    <nav class="my-3 container">
        <ul class="pagination">
            {% if quests.has_previous %}
          <li class="page-item"><a class="page-link" href="?page={{quests.previous_page_number}}">Previous</a></li>
          {% endif %}
          {% for i in quests.paginator.page_range %}
          {% if quests.number == i %}
          <li class="page-item active"><a class="page-link" href="#">{{i}}</a></li>
          {% else %}
          <li class="page-item"><a class="page-link" href="?page={{i}}">{{i}}</a></li>
          {% endif %}
          {% endfor %}
          {% if quests.has_next %}
          <li class="page-item"><a class="page-link" href="?page={{quests.next_page_number}}">Next</a></li>
          {% endif %}
        </ul>
      </nav>
    {% endif %}
{% endblock %}